// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzAHkje9G5GxAbrm1iQNLntmdA7zKzeC4',
    appId: '1:666549115411:web:7312b7afc5288bf6a73de6',
    messagingSenderId: '666549115411',
    projectId: 'csi-hackathon-55684',
    authDomain: 'csi-hackathon-55684.firebaseapp.com',
    storageBucket: 'csi-hackathon-55684.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9-o048q5mIbeAz8UpjDYFqTRM3HjnkOw',
    appId: '1:666549115411:android:a8fa111ab0e102d9a73de6',
    messagingSenderId: '666549115411',
    projectId: 'csi-hackathon-55684',
    storageBucket: 'csi-hackathon-55684.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAUsFjZZvruVyFj51dLVQ3H5JoQVIrlDk',
    appId: '1:666549115411:ios:cd7c6b3245728c3da73de6',
    messagingSenderId: '666549115411',
    projectId: 'csi-hackathon-55684',
    storageBucket: 'csi-hackathon-55684.appspot.com',
    iosBundleId: 'com.example.csiHackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAUsFjZZvruVyFj51dLVQ3H5JoQVIrlDk',
    appId: '1:666549115411:ios:8569052e90d85e9ea73de6',
    messagingSenderId: '666549115411',
    projectId: 'csi-hackathon-55684',
    storageBucket: 'csi-hackathon-55684.appspot.com',
    iosBundleId: 'com.example.csiHackathon.RunnerTests',
  );
}
